### ISSUE TITLE
Making own dataset

### ISSUE THREAD

**Issue by ahsan856jalal** [marcbelmont/satellite-image-object-detection#2]
Hello Sir, 
Link provided for the dataset is no more available. Can you please guide us how to make image dataset and associated groundtruths so that we can use our own custom dataset for this purpose

**Comment by marcbelmont** [comment]
The script `preprocess.py` needs `data/trainingObservations.csv`. It should contain
```
id,image,class,detections
image1.jpg,A,None
image2.jpg,B,1776:520|1824:125
...
```
class is the type of vehicle and 
detections is `x_center_coord:y_center_coord` you can have more than one vehicle in an image. If that's the case separate the coordinates with a `|`
